
run_name: aapl_yahoo_lags_rf
data:
  source: yahoo
  ticker: AAPL
  start: "2016-01-01"
  end: "2025-01-01"
  interval: "1d"
  auto_adjust: false
target:
  column: Adj Close
  horizon: 1
features:
  transforms:
    - type: Returns
    - type: SMA
      params: {window: 5}
    - type: SMA
      params: {window: 20}
    - type: Lag
      params: {col: Adj Close, lags: 5}
model:
  kind: sklearn.random_forest
  params:
    n_estimators: 300
    max_depth: 8
backtest:
  train_size_days: 504
  step_days: 20
metrics: [MAE, RMSE, MAPE, DIR_ACC]
